/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicacotxes_1;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.String.valueOf;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Cotxes;

/**
 *
 * @author 32490.joan23
 */
public class Cotxes_vista extends javax.swing.JFrame {
    ArrayList<Cotxes> lista_cotxes = new ArrayList<Cotxes>();

    /**
     * Creates new form Cotxes_vista
     */
    public Cotxes_vista() {
        initComponents();
        this.jLabelErrorNom.setVisible(false);
        this.jLabelErrorTelf.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRadBut = new javax.swing.ButtonGroup();
        buttonGroupCheck = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelNom = new javax.swing.JLabel();
        jLabelTelf = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jRadioButtonBlanc = new javax.swing.JRadioButton();
        jRadioButtonVermellE = new javax.swing.JRadioButton();
        jRadioButtonGris = new javax.swing.JRadioButton();
        jRadioButtonNegre = new javax.swing.JRadioButton();
        jTextFieldNom = new javax.swing.JTextField();
        jTextFieldTelf = new javax.swing.JTextField();
        jButtonGenerar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabelErrorNom = new javax.swing.JLabel();
        jLabelErrorTelf = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2USB = new javax.swing.JCheckBox();
        jCheckBox3IPOD = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jLabelTitol = new javax.swing.JLabel();
        jRadioButtonVerd = new javax.swing.JRadioButton();
        jRadioButtonVermellR = new javax.swing.JRadioButton();
        jButtonExit = new javax.swing.JButton();
        jButtonNou = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabelNom.setText("Nom del Client:");

        jLabelTelf.setText("Telefon del Client :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Altea 1.4 TSI 125CV (92kw) Arena (21.452 Euros)", "Altea 1.9 TDI 105CV (77kw) Arena (22.299 Euros)", "Altea 1.4 TDI 105CV (77kw) DPF DSG Arena (24.137 Euros)", "Altea 2.0 TDI 140CV (103kw) 6 Vel. Arena (24.274 Euros)", "Altea 2.0 TDI 16V 140CV (92kw) 6 Vel. DSG Arena (25.741 Euros)", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jRadioButtonBlanc.setSelected(true);
        jRadioButtonBlanc.setText("Blanc Candy (0 Euros)");

        jRadioButtonVermellE.setText("Vermell Emoció (152 Euros)");

        jRadioButtonGris.setText("Gris Zenith (400 Euros)");

        jRadioButtonNegre.setText("Negre Magic (400 Euros)");
        jRadioButtonNegre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNegreActionPerformed(evt);
            }
        });

        jTextFieldNom.setToolTipText("Introdueix el teu nom");

        jButtonGenerar.setText("Guardar");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Generar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelErrorNom.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorNom.setText("No pots deixar el nom buit");

        jLabelErrorTelf.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorTelf.setText("No pots deixar el telefon buit");

        jCheckBox1.setText("Instalació telefon Bluetooh + MP3 + antirobatori(8 altaveus en total) (276 Euros)");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2USB.setText("Conexió USB en reposabraços(elimina la conexió AUX-in) (100 Euros)");
        jCheckBox2USB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2USBActionPerformed(evt);
            }
        });

        jCheckBox3IPOD.setText("Conexió iPod en reposabraços(elimina la conexió AUX-in)(100 Euros)");
        jCheckBox3IPOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3IPODActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Portaobjectes interior en el sostre amb pantalla TFT 7\" i conectors RCA(Incompatible amb iPod y USB)(369 Euros)");

        jCheckBox5.setText("Portaobjectes interior en el sostre(98 Euros)");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setText("Seients calefactors + ejectors calefactors + rentafars + montant A calefactat ( + retrovisors posició parking nomes en Reference) (581 Euros)");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("Sistema de navegació blanc i negre + MP3 + antena antirobatori(elimina la conexió AUX-in)(1070 Euros)");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jCheckBox8.setText("SEAT Mediasystem: Sistema de navegació dinamica amb pantalla táctil a color de 6,5\", lector de DVD, disc dur de 30GB, conectivitat Bluetooth i mans en el volant(DVD amb cartografia inclos)(1465 Euros)");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });

        jCheckBox9.setText("Airbags laterals posteriors(253 Euros)");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });

        buttonGroupCheck.add(jCheckBox10);
        jCheckBox10.setText("Fars Bixenon + AFS (835 Euros)");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });

        jLabelTitol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitol.setText("PIMP YOUR CAR");

        jRadioButtonVerd.setText("Verd Natura (400 Euros)");

        jRadioButtonVermellR.setText("Vermell Rubí (400 Euros)");

        jButtonExit.setText("Sortir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jButtonNou.setText("Nou");
        jButtonNou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNouActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        jMenu1.setText("Fitxer");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Guardar com");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Guardar ");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Generar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem3.setText("Sortir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Nou");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(jLabelTitol))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabelTelf, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldNom)
                                            .addComponent(jTextFieldTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelErrorNom)
                                            .addComponent(jLabelErrorTelf)))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonBlanc)
                                            .addComponent(jRadioButtonGris))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButtonNegre)
                                            .addComponent(jRadioButtonVermellE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jRadioButtonVermellR))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jRadioButtonVerd)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jButtonGenerar)
                                        .addGap(28, 28, 28)
                                        .addComponent(jButtonExit)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonNou)
                                        .addGap(40, 40, 40)
                                        .addComponent(jButtonGuardar))))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox9)
                                .addGap(40, 40, 40)
                                .addComponent(jCheckBox10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox2USB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox3IPOD))
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitol)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNom)
                            .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorNom))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTelf)
                            .addComponent(jTextFieldTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelErrorTelf))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonBlanc)
                                .addComponent(jRadioButtonVermellE)
                                .addComponent(jRadioButtonVermellR))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jRadioButtonGris)
                                .addComponent(jRadioButtonVerd))
                            .addComponent(jRadioButtonNegre)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonExit)
                            .addComponent(jButtonNou)
                            .addComponent(jButtonGenerar))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox2USB)
                    .addComponent(jCheckBox3IPOD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
  
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jCheckBox2USBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2USBActionPerformed
        // TODO add your handling code here:
        checkbox();
        
    }//GEN-LAST:event_jCheckBox2USBActionPerformed

    private void jCheckBox3IPODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3IPODActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox3IPODActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        checkbox();
        
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed
        this.jLabelErrorNom.setVisible(false);
        this.jLabelErrorTelf.setVisible(false);
       validacion2();
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        validacion();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonNouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNouActionPerformed
        // TODO add your handling code here:
        this.jTextFieldNom.setText("");
        this.jTextFieldTelf.setText("");
        reset();
        
    }//GEN-LAST:event_jButtonNouActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        validacion();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.jLabelErrorNom.setVisible(false);
        this.jLabelErrorTelf.setVisible(false);
       validacion2();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        escribir_fichero();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jRadioButtonNegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNegreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNegreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cotxes_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cotxes_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cotxes_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cotxes_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cotxes_vista().setVisible(true);
            }
        });
    }

    // Vaidaciones
    public void validacion(){
              if(this.jTextFieldNom.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR,no pots deixar el nom buit");
           this.jLabelErrorNom.setVisible(true);
           this.jButtonGenerar.setEnabled(false);
        }
        if(this.jTextFieldTelf.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR, no pots deixar el telefon buit");
           this.jLabelErrorTelf.setVisible(true);
           this.jButtonGenerar.setEnabled(false);
        }
        if(this.jTextFieldTelf.getText().length()<9){
            JOptionPane.showMessageDialog(null, "ERROR, no son 9 digits");
            this.jButtonGenerar.setEnabled(false);
            
        }
        if(this.jTextFieldTelf.getText().length()>9){
            JOptionPane.showMessageDialog(null, "ERROR, no son 9 digits");
            this.jButtonGenerar.setEnabled(false);
            
            
        }
        if(this.jTextFieldNom.getText().isEmpty()==false & this.jTextFieldTelf.getText().isEmpty()==false &
                this.jTextFieldTelf.getText().length()==9){
            this.jButtonGenerar.setEnabled(true);
            guardar_opciones();
        }
    }
    public void validacion2(){
              if(this.jTextFieldNom.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR,no pots deixar el nom buit");
           this.jLabelErrorNom.setVisible(true);
           this.jButtonGenerar.setEnabled(false);
        }
        if(this.jTextFieldTelf.getText().isEmpty()==true){
            JOptionPane.showMessageDialog(null, "ERROR, no pots deixar el telefon buit");
           this.jLabelErrorTelf.setVisible(true);
           this.jButtonGenerar.setEnabled(false);
        }
        if(this.jTextFieldTelf.getText().length()<9){
            JOptionPane.showMessageDialog(null, "ERROR, no son 9 digits");
            this.jButtonGenerar.setEnabled(false);
            
        }
        if(this.jTextFieldTelf.getText().length()>9){
            JOptionPane.showMessageDialog(null, "ERROR, no son 9 digits");
            this.jButtonGenerar.setEnabled(false);
            
            
        }
        if(this.jTextFieldNom.getText().isEmpty()==false & this.jTextFieldTelf.getText().isEmpty()==false &
                this.jTextFieldTelf.getText().length()==9){
            this.jButtonGenerar.setEnabled(true);
            guardar_opciones();
            escribir2();
        }
    }
    //Para que al seleccionar la opcion incompatible no se pueda seleccionar
    public void checkbox(){
            if(this.jCheckBox2USB.isSelected()){
            this.jCheckBox4.setEnabled(false);   
        }else if(this.jCheckBox3IPOD.isSelected()){
            this.jCheckBox4.setEnabled(false);
        } 
            else{
            this.jCheckBox4.setEnabled(true);
        }
        
    }
    public void reset(){
        if(this.jCheckBox1.isSelected()){
            this.jCheckBox1.setSelected(false);
        }
        if(this.jCheckBox2USB.isSelected()){
            this.jCheckBox2USB.setSelected(false);
            
        }
        if(this.jCheckBox3IPOD.isSelected()){
            this.jCheckBox3IPOD.setSelected(false);
            
        }
        if(this.jCheckBox4.isSelected()){
            this.jCheckBox4.setSelected(false);
        }
        if(this.jCheckBox5.isSelected()){
            this.jCheckBox5.setSelected(false);
        }
        if(this.jCheckBox6.isSelected()){
            this.jCheckBox6.setSelected(false);
        }
        if(this.jCheckBox7.isSelected()){
            this.jCheckBox7.setSelected(false);
        }
        if(this.jCheckBox8.isSelected()){
            this.jCheckBox8.setSelected(false);
        }
        if(this.jCheckBox9.isSelected()){
            this.jCheckBox9.setSelected(false);
        }
        if(this.jCheckBox10.isSelected()){
            this.jCheckBox10.setSelected(false);
        }
        this.jCheckBox4.setEnabled(true);
        if(this.jRadioButtonGris.isSelected()){
            this.jRadioButtonGris.setSelected(false);
        }
        if(this.jRadioButtonNegre.isSelected()){
            this.jRadioButtonNegre.setSelected(false);
        }
        if(this.jRadioButtonVermellE.isSelected()){
            this.jRadioButtonVermellE.setSelected(false);
        }
        if(this.jRadioButtonVermellR.isSelected()){
            this.jRadioButtonVermellR.setSelected(false);
        }
        if(this.jRadioButtonVerd.isSelected()){
            this.jRadioButtonVerd.setSelected(false);
        }
        this.jTextArea1.setText("");
        this.jLabelErrorNom.setVisible(false);
        this.jLabelErrorTelf.setVisible(false);
        this.jButtonGuardar.setEnabled(true);
    }
    public void guardar_opciones(){
        String nom = this.jTextFieldNom.getText();
        String telf = this.jTextFieldTelf.getText();
        this.jTextArea1.append("Nom: ");
        this.jTextArea1.append(nom +"\n");
        this.jTextArea1.append("Telefón: " );
        this.jTextArea1.append(telf +"\n");
        int precio = 0;
        if(this.jRadioButtonBlanc.isSelected()){
            String eleccion_color = ("Blanc Candy");
            this.jTextArea1.append("Color: ");
            this.jTextArea1.append(eleccion_color +"\n");
            precio = precio + 0;
        }
        if(this.jRadioButtonVerd.isSelected()){
            String eleccion_color = ("Verd Natura");
            this.jTextArea1.append("Color: ");
            this.jTextArea1.append(eleccion_color +"\n");
            precio = precio + 400;
        }
        if(this.jRadioButtonNegre.isSelected()){
            String eleccion_color = ("Negre Magic");
            this.jTextArea1.append("Color: ");
            this.jTextArea1.append(eleccion_color +"\n");
            precio = precio + 400;
        }
        if(this.jRadioButtonVermellE.isSelected()){
            String eleccion_color = ("Vermell Emocio");
            this.jTextArea1.append("Color: ");
            this.jTextArea1.append(eleccion_color +"\n");
            precio = precio + 152;
        }
        if(this.jRadioButtonVermellR.isSelected()){
            String eleccion_color = ("Vermell Rubi");
            this.jTextArea1.append("Color: ");
            this.jTextArea1.append(eleccion_color +"\n");
            precio = precio + 400;
        }
        if(this.jRadioButtonGris.isSelected()){
            String eleccion_color = ("Gris Zeniht");
            this.jTextArea1.append("Color: ");
            this.jTextArea1.append(eleccion_color +"\n");
            precio = precio + 400;
        }
        String modeloSelecionado = (String)jComboBox1.getSelectedItem();
            if("Altea 1.4 TSI 125CV (92kw) Arena (21.452 Euros)".equals(modeloSelecionado)){
                this.jTextArea1.append("Model:");
                this.jTextArea1.append("Altea 1.4 TSI 125CV (92kw) Arena" +"\n");
                precio = precio + 21452;
            }
            if("Altea 1.9 TDI 105CV (77kw) Arena (22.299 Euros)".equals(modeloSelecionado)){
                this.jTextArea1.append("Model:");
                this.jTextArea1.append("Altea 1.9 TDI 105CV (77kw) Arena" +"\n");
                precio = precio + 22299;
            }
            if("Altea 1.4 TDI 105CV (77kw) DPF DSG Arena (24.137 Euros))".equals(modeloSelecionado)){
                this.jTextArea1.append("Model:");
                this.jTextArea1.append("Altea 1.4 TDI 105CV (77kw) DPF DSG Arena" +"\n");
                precio = precio + 24137;
            }
            if("Altea 2.0 TDI 140CV (103kw) 6 Vel. Arena (24.274 Euros)".equals(modeloSelecionado)){
                this.jTextArea1.append("Model:");
                this.jTextArea1.append("Altea 2.0 TDI 140CV (103kw) 6 Vel. Arena" +"\n");
                precio = precio + 24274;
            }
            if("Altea 2.0 TDI 16V 140CV (92kw) 6 Vel. DSG Arena (25.741 Euros)".equals(modeloSelecionado)){
                this.jTextArea1.append("Model:");
                this.jTextArea1.append("Altea 2.0 TDI 16V 140CV (92kw) 6 Vel. DSG Arena" +"\n");
                precio = precio + 25741;
            }
        if(this.jCheckBox1.isSelected()){
            String eleccion_opcion = ("Instalació telefon Bluetooh + MP3 + antirobatori(8 altaveus en total)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 276;
        }
        if(this.jCheckBox2USB.isSelected()){
           String eleccion_opcion = ("Conexió USB en reposabraços(elimina la conexió AUX-in)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 100;
        }
        if(this.jCheckBox3IPOD.isSelected()){
            String eleccion_opcion = ("Conexió iPod en reposabraços(elimina la conexió AUX-in)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 100;
        }
        if(this.jCheckBox4.isSelected()){
            String eleccion_opcion = ("Portaobjectes interior en el sostre amb pantalla TFT 7\" i conectors RCA(Incompatible amb iPod y USB)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 369;
        }
        if(this.jCheckBox5.isSelected()){
            String eleccion_opcion = ("Portaobjectes interior en el sostre");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 98;
        }
        if(this.jCheckBox6.isSelected()){
            String eleccion_opcion = ("Seients calefactors + ejectors calefactors + rentafars + montant A calefactat ( + retrovisors posició parking nomes en Reference)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 581;
        }                
        if(this.jCheckBox7.isSelected()){
            String eleccion_opcion = ("Sistema de navegació blanc i negre + MP3 + antena antirobatori(elimina la conexió AUX-in)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 1070;
        }
        if(this.jCheckBox8.isSelected()){
            String eleccion_opcion = ("SEAT Mediasystem: Sistema de navegació dinamica amb pantalla táctil a color de 6,5\", lector de DVD, disc dur de 30GB, conectivitat Bluetooth i mans en el volant(DVD amb cartografia inclos)");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 1465;
        }                       
        if(this.jCheckBox9.isSelected()){
            String eleccion_opcion = ("Airbags laterals posteriors");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 253;
        }
        if(this.jCheckBox10.isSelected()){
           String eleccion_opcion = ("Fars Bixenon + AFS");
            this.jTextArea1.append("Opció: ");
            this.jTextArea1.append(eleccion_opcion +"\n");
            precio = precio + 853;
        }
        this.jTextArea1.append("Preu: ");
        this.jTextArea1.append(String.valueOf(precio)+"\n");
        
    }
    public void escribir_fichero(){
         String comando = "cmd /c  break > c:\\carpetajava\\file.txt";
        Process pr;
        try{
            pr = Runtime.getRuntime().exec(comando);
            //System.out.println(comando);
        }catch(Exception ex){
            System.out.println("Ha ocurrido un error al ejecutar el comando. Error: "+ex);
        }
   
    
      
        try {
    //codejavu ejemplo de filechoser
    //
    
  this.jTextArea1.write(new FileWriter("c:\\carpetajava\\file.txt"));
}
catch (Exception ex) {
  System.out.println("Error");
}
   // TODO add your handling code here:
    }
   

public void escribir2(){

 try
 {
  String nombre="";
  JFileChooser file=new JFileChooser();
  file.showSaveDialog(this);
  File guarda =file.getSelectedFile();
 
  if(guarda !=null)
  {
   /*guardamos el archivo y le damos el formato directamente,
    * si queremos que se guarde en formato doc lo definimos como .doc*/
    FileWriter  save=new FileWriter(guarda+".txt");
   // BufferedWriter bw = new BufferedWriter(save); 
    String p=jTextArea1.getText();
    
      System.out.println(p);
      String [] lineas = p.split("\n");
        System.out.println("Text original:\n"+p);
        System.out.println("Text modificat:\n");
        for(int i=0;i<lineas.length;i++){
           
          
          save.write(lineas[i]); 
          save.write(System.getProperty("line.separator"));
        }
    //save.write(jTextArea1.getText());
    save.close();
    JOptionPane.showMessageDialog(null,
         "El seu arxiu s'ha guardad amb exit",
             "Informació",JOptionPane.INFORMATION_MESSAGE);
    }
 }
  catch(IOException ex)
  {
   JOptionPane.showMessageDialog(null,
        "El seu arxiu no se ha guardat",
           "Advertencia",JOptionPane.WARNING_MESSAGE);
  }
 }

        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupCheck;
    private javax.swing.ButtonGroup buttonGroupRadBut;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNou;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox2USB;
    private javax.swing.JCheckBox jCheckBox3IPOD;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelErrorNom;
    private javax.swing.JLabel jLabelErrorTelf;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelTelf;
    private javax.swing.JLabel jLabelTitol;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButtonBlanc;
    private javax.swing.JRadioButton jRadioButtonGris;
    private javax.swing.JRadioButton jRadioButtonNegre;
    private javax.swing.JRadioButton jRadioButtonVerd;
    private javax.swing.JRadioButton jRadioButtonVermellE;
    private javax.swing.JRadioButton jRadioButtonVermellR;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldNom;
    private javax.swing.JTextField jTextFieldTelf;
    // End of variables declaration//GEN-END:variables
}

